const ERROR_CODES = Object.freeze({
  // General
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_MESSAGE: "INVALID_MESSAGE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Room
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_ALREADY_EXISTS: "ROOM_ALREADY_EXISTS",
  ROOM_FULL: "ROOM_FULL",
  ROOM_PASSWORD_INCORRECT: "ROOM_PASSWORD_INCORRECT",
  ROOM_CLOSED: "ROOM_CLOSED",
  ROOM_OWNER_REQUIRED: "ROOM_OWNER_REQUIRED",
  ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
  NOT_IN_ROOM: "NOT_IN_ROOM",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_OFFLINE: "USER_OFFLINE",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",

  // Peer
  PEER_NOT_FOUND: "PEER_NOT_FOUND",
  PEER_DISCONNECTED: "PEER_DISCONNECTED",
  PEER_BUSY: "PEER_BUSY",

  // File
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  INVALID_FILE: "INVALID_FILE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_OWNER_OFFLINE: "FILE_OWNER_OFFLINE",

  // Download
  DOWNLOAD_NOT_FOUND: "DOWNLOAD_NOT_FOUND",
  DOWNLOAD_CANCELLED: "DOWNLOAD_CANCELLED",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  DOWNLOAD_TIMEOUT: "DOWNLOAD_TIMEOUT",
  DOWNLOAD_ALREADY_RUNNING: "DOWNLOAD_ALREADY_RUNNING",

  // Transfer
  CHUNK_NOT_FOUND: "CHUNK_NOT_FOUND",
  INVALID_CHUNK: "INVALID_CHUNK",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  TRANSFER_TIMEOUT: "TRANSFER_TIMEOUT",
  BUFFER_OVERFLOW: "BUFFER_OVERFLOW",
  RESUME_FAILED: "RESUME_FAILED",

  // WebRTC
  OFFER_FAILED: "OFFER_FAILED",
  ANSWER_FAILED: "ANSWER_FAILED",
  ICE_FAILED: "ICE_FAILED",
  CONNECTION_FAILED: "CONNECTION_FAILED",

  // Redis
  REDIS_ERROR: "REDIS_ERROR",

  // Validation
  INVALID_ROOM_ID: "INVALID_ROOM_ID",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_USERNAME: "INVALID_USERNAME",
  INVALID_PAYLOAD: "INVALID_PAYLOAD"
});

export default ERROR_CODES;