const MESSAGE_TYPES = Object.freeze({
  // Connection
  CONNECT: "CONNECT",
  DISCONNECT: "DISCONNECT",
  HEARTBEAT: "HEARTBEAT",
  HEARTBEAT_ACK: "HEARTBEAT_ACK",

  // Room
  CREATE_ROOM: "CREATE_ROOM",
  ROOM_CREATED: "ROOM_CREATED",

  JOIN_ROOM: "JOIN_ROOM",
  ROOM_JOINED: "ROOM_JOINED",

  LEAVE_ROOM: "LEAVE_ROOM",
  ROOM_LEFT: "ROOM_LEFT",

  KILL_ROOM: "KILL_ROOM",
  ROOM_KILLED: "ROOM_KILLED",

  ROOM_STATE: "ROOM_STATE",

  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",

  // WebRTC Signaling
  OFFER: "OFFER",
  ANSWER: "ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE",

  // File Sharing
  FILE_LIST: "FILE_LIST",
  FILE_ADDED: "FILE_ADDED",
  FILE_REMOVED: "FILE_REMOVED",
  FILE_METADATA: "FILE_METADATA",

  // Download
  DOWNLOAD_REQUEST: "DOWNLOAD_REQUEST",
  DOWNLOAD_ACCEPT: "DOWNLOAD_ACCEPT",
  DOWNLOAD_REJECT: "DOWNLOAD_REJECT",

  DOWNLOAD_STARTED: "DOWNLOAD_STARTED",
  DOWNLOAD_PROGRESS: "DOWNLOAD_PROGRESS",
  DOWNLOAD_COMPLETED: "DOWNLOAD_COMPLETED",
  DOWNLOAD_CANCELLED: "DOWNLOAD_CANCELLED",

  // Resume Support
  RESUME_REQUEST: "RESUME_REQUEST",
  RESUME_ACCEPT: "RESUME_ACCEPT",

  // Chunk Transfer
  CHUNK: "CHUNK",
  CHUNK_ACK: "CHUNK_ACK",
  CHUNK_MISSING: "CHUNK_MISSING",
  CHUNK_COMPLETE: "CHUNK_COMPLETE",

  // Peer Presence
  PEER_ONLINE: "PEER_ONLINE",
  PEER_OFFLINE: "PEER_OFFLINE",

  // Errors
  ERROR: "ERROR",

  // Generic
  SUCCESS: "SUCCESS"
});

export default MESSAGE_TYPES;